# Generated by Django 5.2.5 on 2025-09-13 06:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(help_text='Full name of the admin', max_length=100)),
                ('admin_id', models.CharField(help_text='Unique admin ID in format ADM0001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Admin ID must be in format ADM followed by 4 digits (e.g., ADM0001)', regex='^ADM\\d{4}$')])),
                ('email', models.EmailField(help_text='Admin email address', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff')], default='admin', help_text='Admin role in the system', max_length=20)),
                ('department', models.CharField(help_text='Department where admin is assigned', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Current status of the admin', max_length=20)),
                ('allocation_date', models.DateTimeField(auto_now_add=True, help_text='Date when admin was allocated')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login time of the admin', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, help_text='Superuser who allocated this admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Allocation',
                'verbose_name_plural': 'Admin Allocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
