# Generated by Django 5.2.5 on 2025-09-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminallocation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Login', 'verbose_name_plural': 'Admin Logins'},
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='allocation_date',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminallocation',
            name='status',
        ),
        migrations.AddField(
            model_name='adminallocation',
            name='password',
            field=models.CharField(default='', help_text='Password for admin login', max_length=128),
        ),
        migrations.AddField(
            model_name='adminallocation',
            name='username',
            field=models.CharField(default='', help_text='Username for admin login', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='adminallocation',
            name='admin_name',
            field=models.CharField(default='', help_text='Full name of the admin', max_length=100),
        ),
    ]
