# Generated by Django 5.2.5 on 2025-09-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_adminallocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Donor's full name", max_length=100)),
                ('age', models.PositiveIntegerField(help_text="Donor's age")),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Blood group', max_length=3)),
                ('contact_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('address', models.TextField(blank=True, help_text="Donor's address")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Profile',
                'verbose_name_plural': 'Donor Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
