# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_donorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Admin's full name", max_length=100)),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=20, unique=True)),
                ('department', models.CharField(blank=True, help_text='Department', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('is_super_admin', models.BooleanField(default=False, help_text='Super admin with full privileges')),
                ('is_secondary_admin', models.BooleanField(default=False, help_text='Secondary admin with limited privileges')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this admin account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdminAllocation',
        ),
    ]
