# Generated by Django 5.2.5 on 2025-09-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Donor's age", null=True),
        ),
    ]
