# Generated by Django 5.2.5 on 2025-10-27 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_blooddonation_bloodrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blood Donation', 'verbose_name_plural': 'Blood Donations'},
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='appointment_date',
            field=models.DateField(blank=True, help_text='Scheduled appointment date', null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='next_eligible_date',
            field=models.DateField(blank=True, help_text='Next eligible donation date (90 days after last donation)', null=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Appointment'), ('confirmed', 'Appointment Confirmed'), ('completed', 'Donation Completed'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units stored')),
                ('storage_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(help_text='Expiry date of the blood unit')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Storage location in blood bank', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_unit', to='myapp.blooddonation')),
            ],
            options={
                'verbose_name': 'Blood Bank Unit',
                'verbose_name_plural': 'Blood Bank Units',
                'ordering': ['-storage_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('status_update', 'Status Update'), ('general', 'General')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='myapp.blooddonation')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='myapp.bloodrequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Appointment date')),
                ('start_time', models.TimeField(help_text='Start time of the timeslot')),
                ('end_time', models.TimeField(help_text='End time of the timeslot')),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum number of appointments for this timeslot')),
                ('booked', models.PositiveIntegerField(default=0, help_text='Number of appointments already booked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timeslot is available for booking')),
            ],
            options={
                'verbose_name': 'Timeslot',
                'verbose_name_plural': 'Timeslots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='myapp.timeslot'),
        ),
    ]
