# Generated by Django 5.2.5 on 2025-10-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_blooddonation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booked',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of appointments already booked'),
        ),
    ]
