# Generated by Django 5.2.5 on 2025-10-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_sender_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='initial_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='initial_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('pending_initial', 'Pending Initial Approval'), ('initial_approved', 'Initial Approval - Can Book Slot'), ('slot_confirmed', 'Slot Confirmed - Pending Final Approval'), ('final_approved', 'Final Approved - Donation Completed'), ('rejected', 'Rejected')], default='pending_initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('status_update', 'Status Update'), ('donation_completed', 'Donation Completed'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
