# Generated by Django 5.2.5 on 2025-10-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_blooddonation_final_approved_at_and_more'),
    ]

    operations = [
        # Drop the notification table and recreate it with correct foreign key
        migrations.RunSQL(
            "DROP TABLE IF EXISTS myapp_notification;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('status_update', 'Status Update'), ('donation_completed', 'Donation Completed'), ('general', 'General')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='notifications', to='auth.user')),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='notifications', to='myapp.blooddonation')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='notifications', to='myapp.bloodrequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
